//
//  StyleSheet.swift
//
//  Generated by StyleSheetParser on 04/10/2016.
//  Copyright © 2016 Julien Ducret. All rights reserved.
//

import UIKit

// MARK: - CommonColor enum

public enum CommonColor {

	case grey
	case yellow
	case black
	case offBlack

	var rgba: [CGFloat] {
		switch self {
		case .grey: return [200.0 / 255.0, 200.0 / 255.0, 200.0 / 255.0, 1.0]
		case .yellow: return [245.0 / 255.0, 222.0 / 255.0, 80.0 / 255.0, 1.0]
		case .black: return [0.0 / 255.0, 0.0 / 255.0, 0.0 / 255.0, 1.0]
		case .offBlack: return [20.0 / 255.0, 20.0 / 255.0, 20.0 / 255.0, 1.0]
		}
	}

	var r: CGFloat { return self.rgba[0] }
	var g: CGFloat { return self.rgba[1] }
	var b: CGFloat { return self.rgba[2] }
	var a: CGFloat { return self.rgba[3] }

}

// MARK: - UIColor extension

extension UIColor {

	convenience init(commonColor: CommonColor) {
		self.init(red: commonColor.r, green: commonColor.g, blue: commonColor.b, alpha: commonColor.a)
	}
}

// MARK: - TextStyle enum

public enum TextStyle {

	case navigationTitle
	case bodyDemiBold
	case body
	case placeholder

	public var font: UIFont {

		switch self {
		case .navigationTitle: return UIFont(name: "AvenirNext-DemiBold", size: 16.0)!
		case .bodyDemiBold: return UIFont(name: "AvenirNext-DemiBold", size: 14.0)!
		case .body: return UIFont(name: "AvenirNext-Medium", size: 14.0)!
		case .placeholder: return UIFont(name: "AvenirNext-Medium", size: 14.0)!
		}
	}

	public var color: UIColor {

		switch self {
		case .navigationTitle: return UIColor(commonColor: .offBlack)
		case .bodyDemiBold: return UIColor(commonColor: .offBlack)
		case .body: return UIColor(commonColor: .offBlack)
		case .placeholder: return UIColor(commonColor: .grey)
		}
	}
}
